doc:  update tco
ISPP-07/htld-doc pull request #200
Opened 2024-03-26 13:23 UTC by Marchabar

# Description
- Add sendgrid costs in opex
- Add new TCO excel for 2 years, differentiating between 4 monts of development and the rest of months
- I will update the current tco status for weeks 8 and 9, on Tuesday 2nd April before the evaluation, as usual.
# Checklist:
- [X] I have performed a self-review of my code running `npm run build` and `npm run serve` after pushing the code.
- [X] I have checked that there is no fragile information published unintentionally.

# Screenshot:
![image](https://github.com/ISPP-07/htld-doc/assets/100620336/7a497d62-8190-4916-be8d-adae3c7a3ad0)
![image](https://github.com/ISPP-07/htld-doc/assets/100620336/48250474-e735-493b-a819-0b6c06013b90)

2024-03-29 13:42 UTC, alvgonfri requested changes
It looks correct overall, but there is a small change to do, which you can see below.

Additional note: you said in this PR description that you will be updating the current TCO status for weeks 8 and 9 on Tuesday 2nd April, but if I'm not wrong week 9 starts on 2nd April.

2024-03-29 13:42 UTC, alvgonfri commented on docs/Coste total de la propiedad/TCO.mdx
> +El coste total de la propiedad anual es de **91.2K**.
You should change the word "annual" to say it's now a 2-year TCO.

2024-03-29 19:35 UTC, Marchabar commented
> It looks correct overall, but there is a small change to do, which you can see below.
> 
> Additional note: you said in this PR description that you will be updating the current TCO status for weeks 8 and 9 on Tuesday 2nd April, but if I'm not wrong week 9 starts on 2nd April.

I have updated what you suggested. About the weeks: week 8 is on 19th-25th of March and week 9 is on 26th-1st of April. So, on tuesday 2nd I will update both weeks closing then sprint 2.

2024-03-30 09:25 UTC, alvgonfri approved these changes
Everything is correct now!

2024-03-30 09:25 UTC, merged