doc:BGCC Week 9 feedback
ISPP-07/htld-doc pull request #280
Opened 2024-04-07 17:44 UTC by nicoloboo02

# Description
Week 8 feedback has been added
# Checklist:
- [ ] I have performed a self-review of my code running `npm run build` and `npm run serve` after pushing the code.
- [ ] I have checked that there is no fragile information published unintentionally.

2024-04-07 17:48 UTC, alvarobernal2412 requested changes
The rest of the sections are very good

2024-04-07 17:48 UTC, alvarobernal2412 commented on docs/Anexo I. Aportación a la BGCC/Semana 8.md
> +- Feedback recibido y gestión del mismo\*\*: Se debe incluir una sección que detalle el feedback recibido y cómo se está gestionando, así como una lista priorizada por relevancia.
\*\* What is this?

2024-04-07 17:48 UTC, alvarobernal2412 commented on docs/Anexo I. Aportación a la BGCC/Semana 8.md
> +- Storytelling en el storyboard Se sugiere que el storyboard cuente una historia coherente para mejorar la comprensión del producto.
Quite redundant

2024-04-15 10:51 UTC, nicoloboo02 commented
I deleted it so there is no problem with the content.

2024-04-16 06:20 UTC, alvarobernal2412 approved these changes
Thanks!!

2024-04-16 06:20 UTC, merged